export const ERROR_CODES = {
  VALIDATION: "ERR_VALIDATION",
  INVALID_JSON: "ERR_INVALID_JSON",
  BAD_REQUEST: "ERR_BAD_REQUEST",
  DUPLICATE: "ERR_DUPLICATE",
  NOT_FOUND: "ERR_NOT_FOUND",
  FOREIGN_KEY_CONSTRAINT: "ERR_FOREIGN_KEY_CONSTRAINT",
  DATABASE: "ERR_DATABASE",
  AUTH_REQUIRED: "ERR_AUTH_REQUIRED",
  INVALID_TOKEN: "ERR_INVALID_TOKEN",
  TOKEN_EXPIRED: "ERR_TOKEN_EXPIRED",
  INVALID_REFRESH_TOKEN: "ERR_INVALID_REFRESH_TOKEN",
  ACCOUNT_DISABLED: "ERR_ACCOUNT_DISABLED",
  USER_NOT_FOUND: "ERR_USER_NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  ERR_FORBIDDEN: "ERR_FORBIDDEN",
  UNAUTHORIZED: "ERR_UNAUTHORIZED",
  EMAIL_NOT_VERIFIED: "ERR_EMAIL_NOT_VERIFIED",
  ERR_EMAIL_NOT_VERIFIED: "ERR_EMAIL_NOT_VERIFIED",
  INVALID_OTP: "ERR_INVALID_OTP",
  OTP_EXPIRED: "ERR_OTP_EXPIRED",
  OTP_MAX_ATTEMPTS: "ERR_OTP_MAX_ATTEMPTS",
  OTP_COOLDOWN: "ERR_OTP_COOLDOWN",
  CONFLICT: "ERR_CONFLICT",
  INTERNAL_SERVER: "ERR_INTERNAL_SERVER",
  ORDER_CODE_NOT_FOUND: "ERR_ORDER_CODE_NOT_FOUND",
  INSUFFICIENT_AMOUNT: "ERR_INSUFFICIENT_AMOUNT",
  TRANSACTION_ALREADY_PROCESSED: "ERR_TRANSACTION_ALREADY_PROCESSED",
  WEBHOOK_UNAUTHORIZED: "ERR_WEBHOOK_UNAUTHORIZED",
  LOCK_REQUIRED: "LOCK_REQUIRED",
  PLOT_NOT_AVAILABLE: "PLOT_NOT_AVAILABLE",
  PLOT_ALREADY_LOCKED: "PLOT_ALREADY_LOCKED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Type-safe map từ ErrorCode sang human-readable message.
 * Dùng cho FE error message dictionaries — TypeScript sẽ cảnh báo
 * nếu dùng key không tồn tại trong ErrorCode.
 */
export type ErrorMessageMap = Partial<
  Record<ErrorCode | "ERR_UNKNOWN", string>
>;
