export const PLOTS_HERO_MESSAGES = {
  TAGLINE: "Nông nghiệp số tuần hoàn tại Đà Lạt",
  TITLE_PREFIX: "Sở hữu vườn rau hữu cơ riêng của bạn — ",
  TITLE_HIGHLIGHT: "Giám sát 24/7 từ xa",
  SUBTITLE: "Trải nghiệm cảm giác làm chủ nông trại sinh thái tại Đạ Sar - Đà Lạt ngay trên điện thoại.",
  BULLET_1: "Đội ngũ kỹ sư chăm sóc chuẩn VietGAP.",
  BULLET_2: "Cảm biến IoT truyền dữ liệu độ ẩm, dinh dưỡng theo thời gian thực.",
  CTA_EXPLORE: "Khám phá ô đất trồng ngay",
  CTA_VIDEO: "Xem Video Vườn & Camera Live",
  SOCIAL_PROOF_COUNT: "1.200+",
  SOCIAL_PROOF_TEXT_PREFIX: "Được tin chọn bởi ",
  SOCIAL_PROOF_TEXT_SUFFIX: " gia đình thành thị",
  AVATAR_ADDITIONAL: "+1.2k",
  LIVE_CAMERA_BADGE: "LIVE",
  CAMERA_FEED_TITLE: "Cam 01 • Luống Cà Chua #A-102",
  CAMERA_IMG_ALT: "Vườn xà lách & rau hữu cơ sinh thái Luống #A-102 Đà Lạt",
  NOTIFICATION_SPRAY: "Tưới phun sương lúc 07:30",
  TELEMETRY_HUMIDITY_LABEL: "Độ ẩm đất",
  TELEMETRY_HUMIDITY_VALUE: "68%",
  TELEMETRY_HUMIDITY_STATUS: "Tối ưu",
  TELEMETRY_TEMP_LABEL: "Nhiệt độ",
  TELEMETRY_TEMP_VALUE: "24.2°C",
  TELEMETRY_TEMP_STATUS: "Mát mẻ - Ổn định",
  MODAL_TITLE: "Camera Trực Tiếp – Luống Rau Hữu Cơ #A-102 Đà Lạt",
  MODAL_DESC: "Đường truyền HLS độ trễ thấp giám sát sinh trưởng thực tế ngoài nông trại Đạ Sar.",
  MODAL_VIDEO_DESC: "Camera góc rộng 120° giám sát tự động 24/7, cập nhật tình trạng luống đất theo thời gian thực.",
  MODAL_RESOLUTION: "Độ phân giải: 1080p @ 30fps",
  MODAL_CONNECTION_STATUS: "Kết nối ổn định (Latency 1.2s)",
} as const;
